### ISSUE TITLE
Possibility to change to a different RtMidi binding

### ISSUE THREAD

**Issue by danielappelt** [bergamote/micronux#13]
Your software looks really promising! Great work!

There is this other Python [binding](https://github.com/SpotlightKid/python-rtmidi) to RtMidi which is used for example by [Open Stage Control](https://github.com/jean-emmanuel/open-stage-control/). Maybe it would be feasible to switch?

**Comment by bergamote** [comment]
Hi and thanks for the interest!

At first I was using [amidi](https://linux.die.net/man/1/amidi), then came across [pyrtmidi](https://github.com/patrickkidd/pyrtmidi) and decided to use it. As I was writing the code I stumbled upon python-rtmidi, the one you mentioned, and decided to use that instead. But then I got a bit stuck with something. It's over a year ago now so I can't remember exactly what the problem was (maybe setting a time out on receive) but found a simple workaround with pyrtmidi so I switched back to it.

By switching, do you mean just change the binding, or give an option (command line) for the user to choose which binding to use? All the code that uses the midi module is in micronux/midi.py so it shouldn't be too hard to change the syntax to work with python-rtmidi.  
But to be fair I don't know much about midi and I don't get what the advantage would be?

**Comment by bergamote** [comment]
So I might be wrong but I think I understood why you would want that. Is it because of the module name clash? (both are called `rtmidi`). Posted a question [here](https://stackoverflow.com/questions/65901845/two-pip-installed-modules-have-the-same-name-how-to-select-which-one-is-loaded).

**Comment by danielappelt** [comment]
Hi Kevin! Yes, the situation is exactly as you describe it on Stackoverflow.

I didn't manage to dig deeper yet. What I know is that, for example, in Arch Linux we have a package for each of both bindings in the user repository AUR. They can not be installed at the same time. Actually, I am maintainer of one of the AUR packages (the one you are using now). I needed it to package Open Stage Control some time ago. In the meantime Open Stage Control moved to pyhton-rtmidi though.

Anyway..maybe @Spotlightkid can shed some more light on differences between both bindings and advantages of one over the other?! He is the developer and Arch user repository package maintainer of [python-rtmidi](https://github.com/SpotlightKid/python-rtmidi).

**Comment by bergamote** [comment]
Right, looking at both, I think python-rtmidi's syntax is more python-like and has better documentation (well, basically HAS documentation). The pyrtmidi's syntax is closer to the original C one, but it also implements a bunch of functions/methods from the [JUCE library](https://docs.juce.com/master/classMidiMessage.html) which I think are pretty useful, like `rtmidi.isSySex` and `rtmidi.getRawData` for example. 

I might be mistaken but if both @patrickkidd and @SpotlightKid changed their module name to `pyrtmidi` and `python-rtmidi` respectively, we could import them `... as rtmidi` and there wouldn't be any problem having both installed. 

Maybe setting up a virtual env would be another way to go about it, but I haven't used those yet and I feel it would only work when using pip3 to install packages, is that right?

Finally, I could code both syntaxes then do checks to see which module is loaded and act accordingly. But that seems like quite a bit of work (especially re-implementing the JUCE functions that aren't in python-rtmidi) and without any guarantees that a third person with "kid" in their name isn't gonna put up their own different rtmidi module :D

**Comment by SpotlightKid** [comment]
Hi, python-rtmidi author here. The situation is unfortunate, I agree, all I can say is that python-rtmidi is definitely actively maintained, more up-to-date and better documented.

Regarding the `MidiMessage` module, the functions you mention are trivial or superfluous when using python-rtmidi. `isSysex` just check if the first byte of the message is `0xF0`  and `getRawData` just returns the bytes of the raw MIDI message, which you already have with python-rtmidi anyway when you use `MidiIn.get_message()` (or the receive callback). Other messages in this module are either also really trivial (e.g. all the `isSomething*` methods) or go beyond pure data handling into the realm of music theory (e.g. `isMidiNoteBlack`), which IMHO doesn't belong into a module handling MIDI *in- and output* and there a more specialised modules to do such things, or they make only sense with MIDI *file* events.

**Comment by bergamote** [comment]
Hi, thanks for popping by! Yes, ideally it would be best to just be able to use either and have both installed. Have you two already talked about it? Also, am I missing something when thinking that PyPI could stop this from happening? 

What's coming back to me now is that the real reason why I switched back had to do with the synthesiser itself. On the Micron the keys of the keyboard are used as shortcuts for the menus and when the user sends a sysex it will likely also send one or two random notes. So after clicking "receive" in my program, just grabbing the first message sent from the synth would often fail. After spending some time to understand how timers work, then spending a lot of time trying to get my head around how threads work because the timer was blocking everything, my head was about to explode. Then I noticed that pyrtmidi had an optional time out argument to its "get message" function, so that the function returns the message whenever it receives one or false after the time runs out. By setting that to 1 second I can loop 10 times and as soon as one of the message is a SysEx, break out of the loop. So if the user presses a C at second 2 then sends the program at second 4, they don't have to wait the remaining 6 seconds before getting control again. 
Is there a simple way to do the same thing with python-rtmidi? (but bear in mind that I started learning Python and Qt just to write this program and had never used MIDI before, so like, "trivial" might be relative :D )

Anyway, my biggest concern is ppl breaking other program by following my install instructions so I wrote a [workaround](https://github.com/bergamote/micronux/commit/e14a960e8ee2f3b067253f2187de13268af3f2e8#diff-bb0c3caf12258d2ee55dc27c8a98a868c22938f1e53b572fa467a3db3a067b35) last night. At least it should keep modules from overwriting each other.

**Comment by danielappelt** [comment]
Hey! I am not fluent in Python myself. Still, my advice would be to try to get rid of the timer approach! python-rtmidi and therefore, I guess, the original rtmidi as well as, I assume, pyrtmidi [supports callbacks](https://spotlightkid.github.io/python-rtmidi/rtmidi.html#rtmidi.MidiIn.set_callback). That is you provide a function to rtmidi which gets called everytime a new MIDI message arrives. This way you would just have to check in your callback if you are currently expecting to receive a sysex patch or not and proceede accordingly.

**Comment by SpotlightKid** [comment]
Yes, using an input callback is definitely the better approach, esp. in GUI applications.

 `MidiIn.get_message()` is *not* blocking. If there is no message availabe it returns None. So you'd just call it in a loop until you get the message your looking for and check at each loop iteration whether a timeout has expired. But that would then be blocking and you shouldn't do that in a GUI app.

Register a callback function (don't forget do turn off sysex message filtering, if you want to receive sysex) and in the callback function, trigger a Qt signal to inform your app, that MIDI has arrived. Whether you want to dispatch to different message handlers or filter out certain MIDI message types in the callback handler or in your Qt signal handler is up to you.

**Comment by SpotlightKid** [comment]
Oh, and btw, don't take this personally, but your workaround is horrible. Python modules should not install other packages just by importing them (which happens whenyou start the main script). Don't do that! If you want to help the user, print out a message when you detect the wrong rtmidi version is installed and tell him what command to run to fix it.

**Comment by bergamote** [comment]
Ahah, okay, I changed the workaround from automatic-install to prompt-the-user.

Thanks for the info on callbacks. Ultimately I want to make my program into a real time controller, instead of sending the whole program SysEx everytime a setting changes. It might take a while before I understand the Micron's NRPN logic (it's all in the alesis perl script but I got a bit confused with converting 7bit messages and MSB/LSB). I think I'll swap back the bindings once I get to implementing that.

**Comment by patrickkidd** [comment]
I am the author of [pyrtmidi](https://github.com/patrickkidd/pyrtmidi). 

@SpotlightKid is probably right that `python-rtmidi` is more actively maintained than [pyrtmidi](https://github.com/patrickkidd/pyrtmidi), since [pyrtmidi](https://github.com/patrickkidd/pyrtmidi) hasn't been maintained well these last several years. A 7-year Ph.D. doesn’t make it easy to find time for open source projects... Now that I'm back in the professional programming world I plan on addressing all of the open concerns with [pyrtmidi](https://github.com/patrickkidd/pyrtmidi) before too long. It must still have some niche or another if people are still forking it and posting issues? If not then it should die.

But first some computer theory regardless of tech stack. There are basically three methods for retrieving data from any piece of computer hardware:

1) A non-blocking call. This must be read either periodically via an app-provided timer or constantly in an infinite loop. Timers incur latency but can sometimes be used if the specific time interval itself has a particular meaning to the application, such as an optimal animation interval (~20ms) for an animated CPU meter. Constant back-to-back non-blocking calls in an infinite loop will obviously jump straight to 100% CPU and that method is generally not used.
2) A blocking call (i.e. `select()` or other interrupt-based primitive). This is easy to program but does require the app to make the call in a separate thread so the GUI and other things can operate while the call blocks. 
3) A callback. This is just as useful as (2), but you should expect the callback to be called in a separate thread.

(1) should never be used for midi. You can often convert a blocking call to non-blocking call by passing in 0 as a timeout. But again, there is no real use case for non-blocking calls. [pyrtmidi](https://github.com/patrickkidd/pyrtmidi) implements (2) via `rtmidi.RtMidiIn.getMessage(timeout_ms)` by appropriately freeing the [GIL](https://wiki.python.org/moin/GlobalInterpreterLock) whenever it blocks. That means that performance is good. However, a python interpreter is not actually multithreaded (again, read: [GIL](https://wiki.python.org/moin/GlobalInterpreterLock)) so there is no difference in performance between (2) and (3). The choice is ultimately a matter of personal preference. It is very easy to take any api providing (2) and convert it to (3), and visa-versa with just a little code. pyrtmidi provides some classes to do this because that is easier than providing (3) and there is little actual advantage to adding both methods other than matching the RtMidi api precisely.

I am not sure why one would want to use two separate `RtMidi` wrappers at the same time unless each provided something the other did not. Is that the case with `pyrtmidi` and `python-rtmidi`, or is there a different problem you are trying to address? I am not familiar with `python-rtmidi`, but `pyrtmidi` has been around for about 18 years so I assume `python-rtmidi` was written later because `pyrtmidi` had significant limitations? This last paragraph is potentially a thread-hijack so I understand if you want to ignore it.

Cheers.

**Comment by SpotlightKid** [comment]
@patrickkidd  Thanks for your input. I don't think this is the right place to discuss the history of python-rtmidi here. @bergamote, patrick: if you have specific questions about that or using it, feel free to email me or open an issue at its GitHub page.

**Comment by bergamote** [comment]
Hi and thanks for the breakdown, this will definitely come in handy!

I think it's the perfect place to talk about this as it's what motivated the OP.
I only want to use one wrapper. What I don't want is that when someone installs my program it breaks other programs, and that installing other programs breaks mine.

Now the following ideas are only my opinion and, as should be obvious by now, I have very little knowledge and experience with programming and only vague notions about the ethics of open source.

- @patrickkidd you have a strong argument saying that pyrtmidi existed first. 
- @SpotlightKid you have a strong argument saying that python-rtmidi is actively maintained.
- The biggest barrier to either/both module changing name is that it would break the programs depending on it. But that's actually a very poor argument because as things stand, with the pip modules overwriting each other and distro packages removing each other, programs are already breaking.
- There is value in sticking as close to the original syntax as possible, like pyrtmidi does, and there's also value in making the syntax more python-esque, like python-rtmidi does. The programmer's preference should be the deciding factor, not age or popularity.

One way out I can think of is this (and again, let me stress my ignorance compared to you two, don't be too harsh if it's a terrible idea :D )

- Move pyrtmidi to a package named `pyrtmidi` with the module name `pyrtmidi`
- Keep the package name `python-rtmidi` but change the module name to `python-rtmidi`
- Make the rtmidi package with the rtmidi module be a "dummy" package that just prompts the user, saying that the code needs to be updated to use either pyrtmidi or python-rtmidi.
- Let the program owners update their code by simply adding `... as rtmidi` to their import line.

I think that kinda make sense since both modules are python bindings to rtmidi, as opposed to a full implementation of rtmidi, the module name was always a bit of a misnomer. 
I expect that neither of you are gonna be too hot about doing that, but in the long run it would be healthier for both projects. Let me know what you both think!

**Comment by SpotlightKid** [comment]
I still don' think this is the right place. We can discuss how micronux can handle the current situation best. Anything regarding the future of python-rtmidi or pyrtmidi should be discussed in their respective Github trackers.

**Comment by bergamote** [comment]
@SpotlightKid rightiyo, I initially wanted to post an Issue in both projects but then got a bit star-struck having both your attentions here ;D

**Comment by bergamote** [comment]
@danielappelt let me know if the updated install instructions (and midi.py) resolve the problem. If it does I might close this as it is more of an upstream issue, cheers

**Comment by danielappelt** [comment]
I just tested it. The pyrtmidi installation according to the instructions as well as running the application afterwards works as expected :)
